// Deterministic fallback mock data for instant preview and offline resilience

export const FALLBACK_KPIS = [
  {
    kpi_id: 'kpi_revenue',
    name: 'Gross Revenue',
    current_value: 85516.42,
    baseline_value: 125064.18,
    absolute_change: -39547.76,
    percentage_change: -31.62,
    unit: 'USD',
    is_material: true,
    overall_materiality: 'CRITICAL_ACTIONABLE',
    priority_score: 100,
  },
  {
    kpi_id: 'kpi_conv_rate',
    name: 'Conversion Rate',
    current_value: 0.0163,
    baseline_value: 0.0341,
    absolute_change: -0.0178,
    percentage_change: -52.2,
    unit: '%',
    is_material: true,
    overall_materiality: 'BUSINESS_WARNING',
    priority_score: 85,
  },
  {
    kpi_id: 'kpi_orders',
    name: 'Order Volume',
    current_value: 1420,
    baseline_value: 1980,
    absolute_change: -560,
    percentage_change: -28.28,
    unit: 'COUNT',
    is_material: true,
    overall_materiality: 'BUSINESS_WARNING',
    priority_score: 75,
  },
  {
    kpi_id: 'kpi_aov',
    name: 'Average Order Value (AOV)',
    current_value: 60.22,
    baseline_value: 63.16,
    absolute_change: -2.94,
    percentage_change: -4.65,
    unit: 'USD',
    is_material: false,
    overall_materiality: 'NORMAL',
    priority_score: 20,
  },
  {
    kpi_id: 'kpi_gross_margin',
    name: 'Gross Margin %',
    current_value: 0.412,
    baseline_value: 0.435,
    absolute_change: -0.023,
    percentage_change: -5.29,
    unit: '%',
    is_material: false,
    overall_materiality: 'NORMAL',
    priority_score: 30,
  },
];

export const FALLBACK_INVESTIGATION = {
  investigation_id: 'INV-KPI-REV-20260830-001',
  kpi_id: 'kpi_revenue',
  kpi_name: 'Gross Revenue',
  scenario_id: 'SCENARIO_1_MULTI_FACTOR',
  unit: 'USD',
  baseline_value: 125064.18,
  current_value: 85516.42,
  absolute_change: -39547.76,
  percentage_change: -31.62,
  analytical_method: 'Multiplicative Logarithmic Decomposition',
  baseline_period: { start_date: '2026-08-01', end_date: '2026-08-14' },
  anomaly_period: { start_date: '2026-08-15', end_date: '2026-08-28' },
  materiality: {
    business_materiality: 'MATERIAL',
    statistical_significance: 'STATISTICALLY_SIGNIFICANT',
    z_score: -4.38,
    p_value_approx: 0.001,
  },
  ranked_drivers: [
    {
      driver_name: 'Conversion Rate Decline',
      driver_type: 'Quantitative KPI & Operational',
      contribution_value: -20580.40,
      contribution_percentage: -52.04,
      direction: 'NEGATIVE',
      methodology: 'Logarithmic Bennet Multiplicative Decomposition',
    },
    {
      driver_name: 'Product Mix Shift (Low-Margin Skus)',
      driver_type: 'Dimensional Mix-Shift',
      contribution_value: -9560.12,
      contribution_percentage: -24.17,
      direction: 'NEGATIVE',
      methodology: 'Logarithmic Bennet Mix Effect',
    },
    {
      driver_name: 'Regional Traffic Drop (EU & US-East)',
      driver_type: 'Operational Regional Signal',
      contribution_value: -6420.00,
      contribution_percentage: -16.23,
      direction: 'NEGATIVE',
      methodology: 'Regional Traffic Attribution',
    },
    {
      driver_name: 'Regional Warehouse Stockout (Electronics)',
      driver_type: 'Operational Inventory Signal',
      contribution_value: -2987.24,
      contribution_percentage: -7.55,
      direction: 'NEGATIVE',
      methodology: 'Stockout Lost Opportunity Model',
    },
  ],
  mix_shift_analysis: {
    dimension_name: 'product_category',
    volume_effect_usd: -23500.0,
    mix_shift_effect_usd: -9560.12,
    price_rate_effect_usd: -6487.64,
  },
};

export const FALLBACK_EVIDENCE = {
  kpi_id: 'kpi_revenue',
  status: 'HIGH_CONFIDENCE',
  supporting_evidence: [
    {
      evidence_id: 'EVID-PAY-20260822-a95c4f62',
      issue_type: 'PAYMENT_GATEWAY_TIMEOUT',
      severity: 'HIGH',
      affected_region: 'EU-WEST',
      relevance_score: 0.94,
      sanitized_content: 'Checkout payment gateway timeouts increased to 18.4% during peak hours due to third-party processor latency. Affected user [MASKED_EMAIL] reported repeated 504 errors on Visa/Mastercard.',
      source_table: 'customer_operations_events',
      timestamp: '2026-08-22 14:32:00',
    },
    {
      evidence_id: 'EVID-STK-20260819-3f8b1c09',
      issue_type: 'STOCKOUT',
      severity: 'MEDIUM',
      affected_region: 'US-EAST',
      relevance_score: 0.88,
      sanitized_content: 'Zero inventory on top-selling SKU PRD-4402 resulting in 820 unfulfilled cart checkouts in US-East distribution center.',
      source_table: 'customer_operations_events',
      timestamp: '2026-08-19 09:15:00',
    },
    {
      evidence_id: 'EVID-MKT-20260825-7b2e9d41',
      issue_type: 'CAMPAIGN_OUTAGE',
      severity: 'MEDIUM',
      affected_region: 'ALL',
      relevance_score: 0.82,
      sanitized_content: 'Paid search campaign paused unexpectedly due to billing verification flag, reducing qualified inbound top-of-funnel traffic by 23%.',
      source_table: 'customer_operations_events',
      timestamp: '2026-08-25 11:00:00',
    },
  ],
  contradictory_evidence: [],
};

export const FALLBACK_GOVERNANCE = {
  assessment: {
    kpi_id: 'kpi_revenue',
    confidence_score: 93.7,
    confidence_band: 'HIGH',
    sub_scores: {
      statistical_confidence: 0.96,
      evidence_quality: 0.92,
      data_freshness_quality: 0.98,
      contradictory_evidence_penalty: 0.0,
    },
    driver_assessments: {
      conversion_rate: {
        driver_name: 'Conversion Rate Decline',
        driver_type: 'Quantitative KPI & Operational',
        confidence_score: 94.2,
        confidence_band: 'HIGH',
        justification: 'Strong mathematical alignment corroborated by payment gateway timeout incident telemetry.',
      },
      product_mix: {
        driver_name: 'Product Mix Shift',
        driver_type: 'Dimensional Mix-Shift',
        confidence_score: 89.5,
        confidence_band: 'HIGH',
        justification: 'Logarithmic Bennet formula confirms substantial shift toward discounted accessory lines.',
      },
      stockout: {
        driver_name: 'Regional Stockout',
        driver_type: 'Operational Inventory Signal',
        confidence_score: 87.0,
        confidence_band: 'HIGH',
        justification: 'Corroborated by zero-inventory event records in US-East warehouse.',
      },
    },
  },
  decision: {
    decision: 'PROCEED',
    confidence_score: 93.7,
    reason_summary: 'High statistical confidence (z=-4.38, p<0.001) backed by 3 uncontradicted operational evidence items and fresh SLA data.',
    allowed_actions: ['GENERATE_EXECUTIVE_NARRATIVE', 'GENERATE_ANALYST_NARRATIVE', 'SELECT_RECOMMENDED_ACTIONS'],
  },
};

export const FALLBACK_NARRATIVE = {
  headline: 'Gross Revenue declined -31.62% ($39.5k/day) primarily driven by Payment Gateway Failures and Negative Product Mix Shift.',
  summary: 'During the anomaly period (Aug 15–28), daily revenue decreased from $125.1k to $85.5k (-31.62%). The single largest explanatory driver is a sharp -52.2% drop in conversion rate (contributing -$20.6k / 52.0% of total loss), corroborated by payment gateway timeout surges in EU-West. An unfavorable product mix shift accounted for an additional -$9.6k (24.2%) loss.',
  generation_mode: 'GOVERNED_LLM_SYNTHESIS',
  governance_decision: 'PROCEED',
  key_drivers: [
    {
      driver_name: 'Conversion Rate Decline',
      contribution_value: -20580.40,
      contribution_percentage: -52.04,
      direction: 'NEGATIVE',
    },
    {
      driver_name: 'Product Mix Shift',
      contribution_value: -9560.12,
      contribution_percentage: -24.17,
      direction: 'NEGATIVE',
    },
    {
      driver_name: 'Regional Traffic Drop',
      contribution_value: -6420.00,
      contribution_percentage: -16.23,
      direction: 'NEGATIVE',
    },
  ],
  evidence_citations: [
    {
      evidence_ids: ['EVID-PAY-20260822-a95c4f62'],
      statement: 'EU-West payment gateway timeout rate spiked to 18.4% during peak checkout hours.',
    },
    {
      evidence_ids: ['EVID-STK-20260819-3f8b1c09'],
      statement: 'Warehouse stockouts on high-margin SKU PRD-4402 led to 820 unfulfilled cart checkouts.',
    },
  ],
  caveats: [
    'Baseline calculated over 14 calendar days; seasonal holiday normalization was not required.',
    'Third-party payment telemetry latency was 42ms within SLA bounds.',
  ],
  alternative_hypotheses: [
    'Pure pricing discount hypothesis was tested and rejected (AOV was stable at $60.22 vs $63.16 base).',
    'Return rate surge hypothesis was rejected (returns remained under 2.1%).',
  ],
  recommended_actions: [
    {
      action_id: 'ACT-PAY-001',
      action: 'Initiate Secondary Payment Gateway Failover Protocol for EU-West',
      driver: 'Conversion Rate Decline',
      controllable_lever: 'Payment routing configuration and timeout retry policy',
      expected_impact: 'Recovers estimated $14,000–$18,000/day in dropped checkout transactions',
      decision_right: 'Payments Engineering & Finance Operations Sign-Off',
      owner: 'Payments Operations',
      confidence_band: 'HIGH',
      monitoring_plan: 'Monitor gateway timeout percentage at 5-minute rolling intervals',
      evidence_ids: ['EVID-PAY-20260822-a95c4f62'],
    },
    {
      action_id: 'ACT-INV-002',
      action: 'Expedite Cross-Dock Inventory Rebalancing for High-Margin Electronics SKUs',
      driver: 'Product Mix Shift / Stockout',
      controllable_lever: 'Warehouse transfer prioritization and supplier express delivery',
      expected_impact: 'Restores product mix to baseline, recapturing ~$7,500/day in gross margin',
      decision_right: 'Supply Chain Director Sign-Off',
      owner: 'Inventory Operations',
      confidence_band: 'HIGH',
      monitoring_plan: 'Track SKU availability score daily until buffer reaches >98%',
      evidence_ids: ['EVID-STK-20260819-3f8b1c09'],
    },
    {
      action_id: 'ACT-MKT-003',
      action: 'Reactivate Paid Search Inbound Campaigns with Automated Billing Failover',
      driver: 'Regional Traffic Drop',
      controllable_lever: 'Ad spend allocation & automated backup credit lines',
      expected_impact: 'Restores 4,200 daily qualified sessions within 24 hours',
      decision_right: 'Growth Marketing Lead Approval',
      owner: 'Growth Marketing',
      confidence_band: 'MEDIUM',
      monitoring_plan: 'Track inbound CTR and Cost-Per-Acquisition every 2 hours post-activation',
      evidence_ids: ['EVID-MKT-20260825-7b2e9d41'],
    },
  ],
  telemetry: {
    request_id: 'REQ-DEMO-001',
    kpi_id: 'kpi_revenue',
    persona: 'EXECUTIVE',
    model: 'mock-llm-v1',
    latency_ms: 142.5,
    prompt_tokens: 384,
    completion_tokens: 196,
    estimated_cost_usd: 0.00042,
    cache_hit: false,
  },
};
